# Generated by Django 4.1.1 on 2023-11-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0003_rename_status_roomprofile_availability_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomprofile",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
