# Generated by Django 4.1.1 on 2023-11-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0004_alter_roomprofile_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomprofile", old_name="availability_status", new_name="status",
        ),
        migrations.RemoveField(model_name="roomprofile", name="price",),
    ]
