# Generated by Django 4.1.1 on 2023-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0005_rename_availability_status_roomprofile_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomprofile", old_name="status", new_name="availability_status",
        ),
        migrations.AddField(
            model_name="roomprofile",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
