# Generated by Django 4.1.1 on 2023-11-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0009_remove_room_room_profile_room_room_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="room_profile",),
        migrations.AddField(
            model_name="room",
            name="room_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Room.roomprofile",
            ),
            preserve_default=False,
        ),
    ]
