# Generated by Django 4.1.1 on 2023-11-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0010_remove_room_room_profile_room_room_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomprofile",
            name="services",
            field=models.TextField(default="Food Dry-Cleaning Bed", max_length=200),
            preserve_default=False,
        ),
    ]
