# Generated by Django 4.1.1 on 2023-12-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0011_roomprofile_services"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomprofile", old_name="image", new_name="image1",
        ),
        migrations.AddField(
            model_name="roomprofile",
            name="image2",
            field=models.ImageField(default=None, upload_to="room_image/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomprofile",
            name="image3",
            field=models.ImageField(default=None, upload_to="room_image/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomprofile",
            name="image4",
            field=models.ImageField(default=None, upload_to="room_image/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomprofile",
            name="image5",
            field=models.ImageField(default=None, upload_to="room_image/"),
            preserve_default=False,
        ),
    ]
