# Generated by Django 4.1.1 on 2023-12-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0012_rename_image_roomprofile_image1_roomprofile_image2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomprofile", old_name="image1", new_name="image",
        ),
        migrations.RemoveField(model_name="roomprofile", name="image2",),
        migrations.RemoveField(model_name="roomprofile", name="image3",),
        migrations.RemoveField(model_name="roomprofile", name="image4",),
        migrations.RemoveField(model_name="roomprofile", name="image5",),
    ]
