# Generated by Django 4.1.1 on 2023-11-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ContactUs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="date",
            field=models.DateField(default="2023-11-11"),
            preserve_default=False,
        ),
    ]
