# Generated by Django 4.1.1 on 2023-12-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ContactUs", "0002_contactus_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactus", old_name="first_name", new_name="name",
        ),
        migrations.RemoveField(model_name="contactus", name="last_name",),
    ]
