# Generated by Django 4.1.1 on 2023-11-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Room", "0006_rename_status_roomprofile_availability_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_first_name", models.CharField(max_length=500)),
                ("customer_last_name", models.CharField(max_length=500)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone_number", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "currency",
                    models.CharField(choices=[(1, "USD"), (2, "ETB")], max_length=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Room.roomprofile",
                    ),
                ),
            ],
        ),
    ]
