# Generated by Django 4.1.1 on 2023-11-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0003_remove_booking_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="currency",
            field=models.CharField(
                choices=[("usd", "USD"), ("etb", "ETB")], max_length=10
            ),
        ),
    ]
