# Generated by Django 4.1.1 on 2023-11-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0007_room"),
        ("Booking", "0004_alter_booking_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Room.room"
            ),
        ),
    ]
