# Generated by Django 4.1.1 on 2023-10-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("date", models.DateField(verbose_name="blog_image/")),
            ],
        ),
    ]
