# Generated by Django 4.1.1 on 2023-11-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0008_remove_room_room_profile_room_room_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="room_profile",),
        migrations.AddField(
            model_name="room",
            name="room_profile",
            field=models.ManyToManyField(to="Room.roomprofile"),
        ),
    ]
