# Generated by Django 4.1.1 on 2023-12-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Room", "0014_rename_image_roomprofile_image1_roomprofile_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomprofile",
            name="image6",
            field=models.ImageField(default=None, upload_to="room_image/"),
            preserve_default=False,
        ),
    ]
