# Generated by Django 4.1.1 on 2023-11-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0002_booking_total_amount"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="total_amount",),
    ]
