# Generated by Django 4.1.1 on 2023-11-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0005_alter_booking_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_amount",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
