# Generated by Django 4.1.1 on 2023-12-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0006_booking_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
